// Regenerates src/components/sig-paths.ts — the animated signature wordmark.
//
// "Jon Wolf" set in Ms Madi (Google Fonts, OFL), extracted as real outlines
// via opentype.js, plus a hand-tuned tapered underline swash drawn to match
// the script's flow. Run from repo root:
//
//   node scripts/gen-logo.mjs
//
// Font expected at scripts/fonts/MsMadi-Regular.ttf

import { readFile, writeFile } from 'node:fs/promises';
import opentype from 'opentype.js';

const TEXT = 'Jon Wolf';
const SIZE = 110; // px font size in SVG units
const PAD = 6;

const buf = await readFile(new URL('./fonts/MsMadi-Regular.ttf', import.meta.url));
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));

const scale = SIZE / font.unitsPerEm;
const baseline = 96; // tuned so ascenders clear the top after measuring

// ---- Letters: per-glyph outlines with kerning, skipping the space ----
const letters = [];
let x = PAD;
const chars = [...TEXT];
for (let i = 0; i < chars.length; i++) {
  const ch = chars[i];
  const glyph = font.charToGlyph(ch);
  if (ch !== ' ') {
    const path = glyph.getPath(x, baseline, SIZE);
    const bb = path.getBoundingBox();
    letters.push({
      char: ch,
      d: path.toPathData(1),
      x1: +bb.x1.toFixed(1),
      y1: +bb.y1.toFixed(1),
      x2: +bb.x2.toFixed(1),
      y2: +bb.y2.toFixed(1),
    });
  }
  x += glyph.advanceWidth * scale;
  if (i < chars.length - 1) {
    x += font.getKerningValue(glyph, font.charToGlyph(chars[i + 1])) * scale;
  }
}

const minX = Math.min(...letters.map((l) => l.x1));
const maxX = Math.max(...letters.map((l) => l.x2));
const minY = Math.min(...letters.map((l) => l.y1));
const maxY = Math.max(...letters.map((l) => l.y2));

// ---- Underline swash: a tapered pen stroke swept under the name ----
// Spine: single cubic running just below the baseline, bowing down slightly
// mid-word and finishing with a small upward flick past the word's end.
// Descenders (J, f) are allowed to cross it — that's how a signature sits.
// Span: from the first "o" (of Jon) through the "l" (of Wolf)
const oLetter = letters[1];
const lLetter = letters[5];
const sy = baseline + 18;
const sx0 = oLetter.x1;
const sx1 = lLetter.x2;
const spine = {
  p0: { x: sx0, y: sy + 6 },
  c1: { x: sx0 + (sx1 - sx0) * 0.3, y: sy + 16 },
  c2: { x: sx0 + (sx1 - sx0) * 0.78, y: sy + 10 },
  p1: { x: sx1, y: sy - 6 },
};

const cubic = (t, a, b, c, d) => {
  const u = 1 - t;
  return u * u * u * a + 3 * u * u * t * b + 3 * u * t * t * c + t * t * t * d;
};
const cubicD = (t, a, b, c, d) => {
  const u = 1 - t;
  return 3 * u * u * (b - a) + 6 * u * t * (c - b) + 3 * t * t * (d - c);
};

const at = (t) => ({
  x: cubic(t, spine.p0.x, spine.c1.x, spine.c2.x, spine.p1.x),
  y: cubic(t, spine.p0.y, spine.c1.y, spine.c2.y, spine.p1.y),
});
const normal = (t) => {
  const dx = cubicD(t, spine.p0.x, spine.c1.x, spine.c2.x, spine.p1.x);
  const dy = cubicD(t, spine.p0.y, spine.c1.y, spine.c2.y, spine.p1.y);
  const len = Math.hypot(dx, dy) || 1;
  return { x: -dy / len, y: dx / len };
};
// Pen pressure: quick entry ramp, full weight early, draining to a point.
const width = (t) => {
  const entry = Math.min(1, t / 0.07);
  const body = Math.pow(1 - Math.max(0, t - 0.07) / 0.93, 0.8);
  return 5.4 * entry * body + 0.25;
};

const STEPS = 48;
const top = [];
const bot = [];
for (let i = 0; i <= STEPS; i++) {
  const t = i / STEPS;
  const p = at(t);
  const n = normal(t);
  const w = width(t) / 2;
  top.push(`${(p.x + n.x * w).toFixed(1)} ${(p.y + n.y * w).toFixed(1)}`);
  bot.push(`${(p.x - n.x * w).toFixed(1)} ${(p.y - n.y * w).toFixed(1)}`);
}
const swashD = `M${top.join('L')}L${bot.reverse().join('L')}Z`;
const swashBB = {
  x1: +(Math.min(sx0, sx1) - 4).toFixed(1),
  y1: +(sy - 14).toFixed(1),
  x2: +(Math.max(sx0, sx1) + 4).toFixed(1),
  y2: +(sy + 22).toFixed(1),
};
const spineD = `M ${spine.p0.x.toFixed(0)} ${spine.p0.y.toFixed(0)} C ${spine.c1.x.toFixed(0)} ${spine.c1.y.toFixed(0)}, ${spine.c2.x.toFixed(0)} ${spine.c2.y.toFixed(0)}, ${spine.p1.x.toFixed(0)} ${spine.p1.y.toFixed(0)}`;

// ---- Viewbox: tight around letters + swash with breathing room ----
const vbX = Math.floor(Math.min(minX, swashBB.x1) - PAD);
const vbY = Math.floor(minY - PAD);
const vbW = Math.ceil(Math.max(maxX, swashBB.x2) + PAD) - vbX;
const vbH = Math.ceil(Math.max(maxY, swashBB.y2) + PAD) - vbY;

const out = `// AUTO-GENERATED by scripts/gen-logo.mjs — do not hand-edit.
// "Jon Wolf" outlines from Ms Madi (OFL); tapered underline swash generated
// to match the script's flow, placed as a single stroke below the word.

export interface SigLetter {
  char: string;
  d: string;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export const VIEWBOX = '${vbX} ${vbY} ${vbW} ${vbH}';

export const LETTERS: SigLetter[] = ${JSON.stringify(letters)};

export const SWASH = ${JSON.stringify({ d: swashD, ...swashBB })};

/** Pen spine for the swash reveal mask — follows the swash's arc. */
export const SWASH_SPINE = ${JSON.stringify(spineD)};
`;

await writeFile(new URL('../src/components/sig-paths.ts', import.meta.url), out);
console.log(`letters: ${letters.map((l) => l.char).join('')}`);
console.log(`bbox: x ${minX.toFixed(0)}..${maxX.toFixed(0)}, y ${minY.toFixed(0)}..${maxY.toFixed(0)}`);
console.log(`viewBox: ${vbX} ${vbY} ${vbW} ${vbH}`);
